server:
  port: 8092
spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: dytni
    password: 1331
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml